[Close]
Normal=breeze-close.svg
Hover=breeze-close-hover.svg
Pressed=breeze-close-active.svg
Backdrop=breeze-close.svg

[Maximize]
Normal=breeze-maximize.svg
Hover=breeze-maximize-hover.svg
Pressed=breeze-maximize-active.svg
Backdrop=breeze-maximize.svg

[Restore]
Normal=breeze-maximized.svg
Hover=breeze-maximized-hover.svg
Pressed=breeze-maximized-active.svg
Backdrop=breeze-maximized.svg

[Minimize]
Normal=breeze-minimize.svg
Hover=breeze-minimize-hover.svg
Pressed=breeze-minimize-active.svg
Backdrop=breeze-minimize.svg

[Decoration]
BorderRadius=4
Source=CSD.qml

